from .main_menu import *
from .milling import *
from .contour import *
from .tools import *
from .drilling import *
from .drilling_menu import *
from .face import *
from .materials import *
from .direction import *
from .allowance import *
from .overlap import *
from .threading import *
from .catalogs import *
from .reference import *
from .utils import *
from .machining import *
from .holes import *
from .milling_tools import *